// If the jupiter instruction's sender is my account, that means it hasn't been manipulated.
// Thus, we could avoid getting into its details.
// We still need to check every other instruction in the transaction to make sure there's no a Transfer (for example) to another person.

const { PublicKey, VersionedTransaction } = require("@solana/web3.js");

const InstructionParser = require("./instruction-parser");

const JUPITER_V6_PROGRAM_ID = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4";

const decodeTransaction = (base64TransactionData) => {
  const decodedTransactionData = Buffer.from(base64TransactionData, "base64");

  const transaction = VersionedTransaction.deserialize(decodedTransactionData);

  const instructionParser = new InstructionParser(
    new PublicKey(JUPITER_V6_PROGRAM_ID)
  );

  const jupiterInstructions = instructionParser.getJupiterInstructions({
    transaction,
  });

  return instructionParser.getInAndOutAmounts(jupiterInstructions);
};

// const base64TransactionData =
//   "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAHEnEFiG4DTZRCbmnlsIoI3aN48Z+uAD3YHPdxGxDNU+kyCCGP/EB23+TrlVGaWIyyyFGhfpkVZugj+8HY/grfA1hKW+R5sbYgVj8qiLTr4aKTOZunWL2wNcQdejzeAMhoGG4W91d2pdzUEPxLmDjV21GXaL4M6y1PA1voDK7/q0dph7Uj+ncbLnnXrncZ0M9fcpfQPh1Y9fJm+wF6ZvdeXAecGzJrCZxDIwtKtVHyjv75vJQe8cvEL9m7bNTO4oxerrUUipMzi8CShVjAG9xx5AQwTg5UMM0U25fL5xbpLZS3w0AKZf83ZsMb7wHrKRBfNI6Q+Umh9gwz6TsuMr8np7TJD7R7MrykQ+ZBtfBnxPPc7nb9gAKhPbS/SITgDsPVtN98WEPD+gf4+4FB1muMC+gCWv8y3vpmYTDusMu6aGBP9JXopPY5L9d+tnaIZjNyCJX8sUL3snd3L4/2yF45wKsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMGRm/lIRcy/+ytunLDm+e8jOW7xfcSayxDmzpAAAAABHnVW/IxwG7udMVuzmgVB/2xst6j9I5RArHNola8E48G3fbh12Whk9nL4UbO63msHLSF7V9bN5E6jPWFfv8AqYKX5UT/REBqE7f6ZMLP+j7G4V34k14Ax0Fw3q7wE/N9jJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+Fm0P/on9df2SnTAmx8pWHneSwmrNt/J3VFLMhqns4zl6JlzzGIbQ/h8ud+W3wt4exIn9uhUGnXBhVblt1ksY+8pBwwABQLAXBUADAAJAwQXAQAAAAAAEAYABQAfCw4BAQsCAAUMAgAAABNaLwQAAAAADgEFARENOw4PAAUECgYfJgcNEQ0jGSMYFgQIHyUXIw8ODiQjAgEDDSgnGw8ICR0cGh4OKispISATFAoJFRIPIg4NLcEgmzNB1pyBBgMAAAAmZAABGWQBAhIAZAIDE1ovBAAAAADiR5cAAAAAAMgAVQ4DBQAAAQkDGbsIyLJsYYdbyL8yjviU3vsNvxY5X5NSTo2OQ6zTwowEIBsZHAQsHxcdR2RvASBPDyQ4Vj7qqZ/Un04uGpL0gmT9xn8RbtPLAQgE9fn09wR5dPZzs5REVmID5dhx3eCRpJ7vc4qAfNlwSCRZfc4gCNv0gAgFLCguLTAFJyIvKxY=";
const base64TransactionData =
  "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAHD3EFiG4DTZRCbmnlsIoI3aN48Z+uAD3YHPdxGxDNU+kyOAHIkXP+jIl40CFgl+ft6tNmzrEkeOe4BXS/9y4fqJA9t1pWG6qWtPmFmciR1xbrt4IW+b1nNcz2N5abYbCcsFADLL1zkJzVmaQIzSY+ENLjwa+LkcC92gQApzi7UU4MZ0EED+QHqrBQRqB+cbMfYZjXZcTe9r+CfdbguirL8P6cGzJrCZxDIwtKtVHyjv75vJQe8cvEL9m7bNTO4oxerqLzz52eQbJCPxLYiSm4iaKNc8ncsyvelkk2GmiDnfwWuAcMGg4jPq0aZZP6v3Brdi2qi4si/TX8grKcaVzhOcQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMGRm/lIRcy/+ytunLDm+e8jOW7xfcSayxDmzpAAAAABHnVW/IxwG7udMVuzmgVB/2xst6j9I5RArHNola8E48G3fbh12Whk9nL4UbO63msHLSF7V9bN5E6jPWFfv8AqVE+LF26QsO9gzDavYNO6ZflUDWJ+gBV9eCQ5OcuzAMSjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+Fm0P/on9df2SnTAmx8pWHneSwmrNt/J3VFLMhqns4zl6EBc4PGS1k+aRV3SB6pvqgtLDN0j7tnUF/HL7U58jShwBwkABQLAXBUACQAJAwQXAQAAAAAADQYABQAeCAsBAQgCAAUMAgAAAOhq3wMAAAAACwEFAREKPQsMAAUEAgYeJAMKDgodEx0PEAQHHx4RHQwLCyAdEgoiIRcVBwEUFgwjCwodGh0YHAECJCUZHQwLCyAdGwotwSCbM0HWnIEDAwAAACZkAAESAWQBAiZkAgPoat8DAAAAAJNfmAAAAAAAyABVCwMFAAABCQO2EQH3pX6jHRIeCR18elUtxl6cnloTSkJQbMfZtiPHPgUTEhARWgQPWFtZ70cJSZx3usgQE28gD08xGFASErdDSjRf7Zy1CStpJFsEuLS2mgOZmLN4v8D6Ccv8yXNcO0Dn7waISjBP1gziKggY0opcgUhDYgVNRUxHSgJGSA==";
const data = decodeTransaction(base64TransactionData);
console.log(data);
