name: Test My Custom Action

on:
  pull_request:
    types: [closed]

jobs:
  merge-chain:
    if: github.event.pull_request.merged == true
    timeout-minutes: 10
    name: Mirror issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge chain
        uses: ExodusMovement/mirror-issue-action@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
